<?php
declare(strict_types=1);

// Evervault SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

EvervaultUtility::setRegistrar(function (EvervaultUtility $u): void {
    $u->clean = [EvervaultClean::class, 'call'];
    $u->done = [EvervaultDone::class, 'call'];
    $u->make_error = [EvervaultMakeError::class, 'call'];
    $u->feature_add = [EvervaultFeatureAdd::class, 'call'];
    $u->feature_hook = [EvervaultFeatureHook::class, 'call'];
    $u->feature_init = [EvervaultFeatureInit::class, 'call'];
    $u->fetcher = [EvervaultFetcher::class, 'call'];
    $u->make_fetch_def = [EvervaultMakeFetchDef::class, 'call'];
    $u->make_context = [EvervaultMakeContext::class, 'call'];
    $u->make_options = [EvervaultMakeOptions::class, 'call'];
    $u->make_request = [EvervaultMakeRequest::class, 'call'];
    $u->make_response = [EvervaultMakeResponse::class, 'call'];
    $u->make_result = [EvervaultMakeResult::class, 'call'];
    $u->make_point = [EvervaultMakePoint::class, 'call'];
    $u->make_spec = [EvervaultMakeSpec::class, 'call'];
    $u->make_url = [EvervaultMakeUrl::class, 'call'];
    $u->param = [EvervaultParam::class, 'call'];
    $u->prepare_auth = [EvervaultPrepareAuth::class, 'call'];
    $u->prepare_body = [EvervaultPrepareBody::class, 'call'];
    $u->prepare_headers = [EvervaultPrepareHeaders::class, 'call'];
    $u->prepare_method = [EvervaultPrepareMethod::class, 'call'];
    $u->prepare_params = [EvervaultPrepareParams::class, 'call'];
    $u->prepare_path = [EvervaultPreparePath::class, 'call'];
    $u->prepare_query = [EvervaultPrepareQuery::class, 'call'];
    $u->graphql_body = [EvervaultGraphql::class, 'body'];
    $u->graphql_errors = [EvervaultGraphql::class, 'errors'];
    $u->result_basic = [EvervaultResultBasic::class, 'call'];
    $u->result_body = [EvervaultResultBody::class, 'call'];
    $u->result_headers = [EvervaultResultHeaders::class, 'call'];
    $u->transform_request = [EvervaultTransformRequest::class, 'call'];
    $u->transform_response = [EvervaultTransformResponse::class, 'call'];
});
